<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<Reference Include="Accessibility">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Accessibility.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="com.cqf.urpvolumetricfog.runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\com.cqf.urpvolumetricfog.runtime.dll</HintPath>
		</Reference>
		<Reference Include="Facepunch.Steamworks.Win64">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Facepunch.Steamworks.Win64.dll</HintPath>
		</Reference>
		<Reference Include="FMODUnity">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\FMODUnity.dll</HintPath>
		</Reference>
		<Reference Include="FMODUnityHaptics">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\FMODUnityHaptics.dll</HintPath>
		</Reference>
		<Reference Include="FMODUnityResonance">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\FMODUnityResonance.dll</HintPath>
		</Reference>
		<Reference Include="glTFast">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\glTFast.dll</HintPath>
		</Reference>
		<Reference Include="glTFast.Documentation.Examples">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\glTFast.Documentation.Examples.dll</HintPath>
		</Reference>
		<Reference Include="glTFast.dots">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\glTFast.dots.dll</HintPath>
		</Reference>
		<Reference Include="glTFast.Export">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\glTFast.Export.dll</HintPath>
		</Reference>
		<Reference Include="glTFast.Newtonsoft">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\glTFast.Newtonsoft.dll</HintPath>
		</Reference>
		<Reference Include="lootlocker.lootlockersdk.runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\lootlocker.lootlockersdk.runtime.dll</HintPath>
		</Reference>
		<Reference Include="Mono.Data.Sqlite">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Mono.Data.Sqlite.dll</HintPath>
		</Reference>
		<Reference Include="Mono.Posix">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Mono.Posix.dll</HintPath>
		</Reference>
		<Reference Include="Mono.WebBrowser">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Mono.WebBrowser.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="Novell.Directory.Ldap">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Novell.Directory.Ldap.dll</HintPath>
		</Reference>
		<Reference Include="Ookii.Dialogs">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Ookii.Dialogs.dll</HintPath>
		</Reference>
		<Reference Include="pantaloon.sdk">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\pantaloon.sdk.dll</HintPath>
		</Reference>
		<Reference Include="SkiaSharp">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\SkiaSharp.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Addressables">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Addressables.dll</HintPath>
		</Reference>
		<Reference Include="Unity.AI.Navigation">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.AI.Navigation.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Burst.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst.Unsafe">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Burst.Unsafe.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Collections">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Collections.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Collections.LowLevel.ILSupport">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.InputSystem.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem.ForUI">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.InputSystem.ForUI.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InternalAPIEngineBridge.004">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.InternalAPIEngineBridge.004.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Mathematics">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Mathematics.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Multiplayer.Center.Common">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Multiplayer.Center.Common.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Profiling.Core">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Profiling.Core.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Recorder.Base">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Recorder.Base.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Recorder">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Recorder.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Rendering.LightTransport.Runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Rendering.LightTransport.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Core.Runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Core.Runtime.Shared">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipelines.Core.Runtime.Shared.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Core.ShaderLibrary">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipelines.Core.ShaderLibrary.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.GPUDriven.Runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipelines.GPUDriven.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Universal.2D.Runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipelines.Universal.2D.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Universal.Config.Runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipelines.Universal.Config.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Universal.Runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Universal.Shaders">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.RenderPipelines.Universal.Shaders.dll</HintPath>
		</Reference>
		<Reference Include="Unity.ResourceManager">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.ResourceManager.dll</HintPath>
		</Reference>
		<Reference Include="Unity.ScriptableBuildPipeline">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.ScriptableBuildPipeline.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Timeline">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.Timeline.dll</HintPath>
		</Reference>
		<Reference Include="Unity.UnifiedRayTracing.Runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.UnifiedRayTracing.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.VisualScripting.Antlr3.Runtime">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.VisualScripting.Antlr3.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.VisualScripting.Core">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.VisualScripting.Core.dll</HintPath>
		</Reference>
		<Reference Include="Unity.VisualScripting.DocCodeExamples">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.VisualScripting.DocCodeExamples.dll</HintPath>
		</Reference>
		<Reference Include="Unity.VisualScripting.Flow">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.VisualScripting.Flow.dll</HintPath>
		</Reference>
		<Reference Include="Unity.VisualScripting.State">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\Unity.VisualScripting.State.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AccessibilityModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.AccessibilityModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AdaptivePerformanceModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.AdaptivePerformanceModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AMDModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.AMDModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AndroidJNIModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.AndroidJNIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ARModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ARModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClothModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ClothModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterInputModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ClusterInputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterRendererModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ClusterRendererModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ContentLoadModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ContentLoadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CrashReportingModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.CrashReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DirectorModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.DirectorModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DSPGraphModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.DSPGraphModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GameCenterModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GIModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.GIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GraphicsStateCollectionSerializerModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.GraphicsStateCollectionSerializerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GridModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.GridModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HierarchyCoreModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.HierarchyCoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HierarchyModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.HierarchyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HotReloadModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.HotReloadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IdentifiersModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.IdentifiersModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputForUIModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.InputForUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.InputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InsightsModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.InsightsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.JSONSerializeModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.LocalizationModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.LocalizationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.MarshallingModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.MarshallingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.MultiplayerModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.MultiplayerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.NVIDIAModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.NVIDIAModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ParticleSystemModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PerformanceReportingModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.PerformanceReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Physics2DModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsBackendPhysXModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.PhysicsBackendPhysXModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PropertiesModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.PropertiesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.RenderAs2DModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.RenderAs2DModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ScreenCaptureModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ShaderRuntimeModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ShaderRuntimeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ShaderVariantAnalyticsModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.ShaderVariantAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SharedInternalsModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.SharedInternalsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteMaskModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteShapeModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.SpriteShapeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.StreamingModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.StreamingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubstanceModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.SubstanceModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubsystemsModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.SubsystemsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainPhysicsModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreFontEngineModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreTextEngineModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TilemapModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TLSModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.TLSModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIElementsModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UmbraModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UmbraModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsCommonModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityConnectModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityConnectModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityConsentModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityConsentModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityCurlModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityCurlModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityTestProtocolModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityTestProtocolModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAudioModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestTextureModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestWWWModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VectorGraphicsModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.VectorGraphicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VehiclesModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.VehiclesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VFXModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.VFXModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VideoModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VirtualTexturingModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.VirtualTexturingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VRModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.VRModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.WindModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.WindModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.XRModule">
			<HintPath>$(GamePath)/BOXROOM_Data\Managed\UnityEngine.XRModule.dll</HintPath>
		</Reference>
		<Reference Include="MelonLoader">
			<HintPath>$(GamePath)/MelonLoader\net35\MelonLoader.dll</HintPath>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(GamePath)/MelonLoader\net35\0Harmony.dll</HintPath>
		</Reference>

	</ItemGroup>

	<Target Name="CopyToMods" AfterTargets="Build">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GamePath)\Mods" />
	</Target>

</Project>
